apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: shoppe-master-microservices-nest-next
build:
  artifacts:
    # PAYMENT MS 
    - image: yasniel1408/payment-ms
      context: payment-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # INVENTORY MS 
    - image: yasniel1408/inventory-ms
      context: inventory-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # IDENTITY MS 
    - image: yasniel1408/identity-ms
      context: identity-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # ECOMMERCE MS 
    - image: yasniel1408/ecommerce-ms
      context: ecommerce-ms
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # API GATEWAY 
    - image: yasniel1408/api-gateway
      context: api-gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
    # CLIENT WEB APP 
    - image: yasniel1408/web-app
      context: web-app
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"
          - dest: .
            src: "src/**/*.tsx"
          - dest: .
            src: "src/**/*.js"
          - dest: .
            src: "src/**/*.css"
manifests:
  rawYaml:
    - infra/k8s/*
