apiVersion: v1
kind: Service
metadata:
  name: payment-ms-service
spec:
  selector:
    app: payment-ms
  type: ClusterIP
  ports:
    - name: payment-ms
      protocol: TCP
      port: 3000
      targetPort: 3000
