apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-ms
  template:
    metadata:
      labels:
        app: payment-ms
    spec:
      automountServiceAccountToken: false
      containers:
        - name: payment-ms
          image: "yasniel1408/payment-ms:latest"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "600Mi"
              cpu: "200m"
          # env:
          #   - name: JWT_KEY # esta configuaracion de aca es para que tome los valores que hay del secret en el cluster y los tome como variable de entorno dentro del contenedor
          #     valueFrom:
          #       secretKeyRef:
          #         name: jwt-secret
          #         key: JWT_KEY
