export enum CurrencyType {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  JPY = 'JPY',
  CNY = 'CNY',
  KRW = 'KRW',
  BTC = 'BTC',
  ETH = 'ETH',
  LTC = 'LTC',
  UYU = 'UYU',
  ARS = 'ARS',
  BRL = 'BRL',
  CLP = 'CLP',
  MXN = 'MXN',
  PEN = 'PEN',
  VES = 'VES',
}
