apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-ms
  template:
    metadata:
      labels:
        app: inventory-ms
    spec:
      # automountServiceAccountToken: false
      containers:
        - name: inventory-ms
          image: "yasniel1408/inventory-ms:latest"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "800m"
          # env:
          #   - name: JWT_KEY # esta configuaracion de aca es para que tome los valores que hay del secret en el cluster y los tome como variable de entorno dentro del contenedor
          #     valueFrom:
          #       secretKeyRef:
          #         name: jwt-secret
          #         key: JWT_KEY
