apiVersion: v1
kind: Service
metadata:
  name: inventory-ms-service
spec:
  selector:
    app: inventory-ms
  type: ClusterIP
  ports:
    - name: inventory-ms
      protocol: TCP
      port: 3000
      targetPort: 3000
