apiVersion: v1
kind: Service
metadata:
  name: inventory-mysql-service
spec:
  selector:
    app: inventory-mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  type: ClusterIP