apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-mysql-deployment
spec:
  selector:
    matchLabels:
      app: inventory-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: inventory-mysql
    spec:
      automountServiceAccountToken: false
      containers:
      - image: mysql:5.7
        name: inventory-mysql
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: admin  # Cambia esto por una contraseña segura
        - name: MYSQL_DATABASE
          value: admin  # Nombre de la base de datos a crear
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: inventory-mysql-pvc

