apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  type: ClusterIP
  ports:
    - name: web-app
      protocol: TCP
      port: 3000
      targetPort: 3000
