apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  type: ClusterIP
  ports:
    - name: client
      protocol: TCP
      port: 5672
      targetPort: 5672