apiVersion: v1
kind: Service
metadata:
  name: identity-ms-service
spec:
  selector:
    app: identity-ms
  type: ClusterIP
  ports:
    - name: identity-ms
      protocol: TCP
      port: 3000
      targetPort: 3000
