apiVersion: v1
kind: Service
metadata:
  name: ecommerce-mongodb-service
spec:
  selector:
    app: ecommerce-mongodb
  type: ClusterIP
  ports:
    - name: ecommerce-mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017