apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-ms
  template:
    metadata:
      labels:
        app: ecommerce-ms
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ecommerce-ms
          image: "yasniel1408/ecommerce-ms:latest"
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "1"
          # env:
          #   - name: JWT_KEY # esta configuaracion de aca es para que tome los valores que hay del secret en el cluster y los tome como variable de entorno dentro del contenedor
          #     valueFrom:
          #       secretKeyRef:
          #         name: jwt-secret
          #         key: JWT_KEY
