apiVersion: v1
kind: Service
metadata:
  name: ecommerce-ms-service
spec:
  selector:
    app: ecommerce-ms
  type: ClusterIP
  ports:
    - name: ecommerce-ms
      protocol: TCP
      port: 3000
      targetPort: 3000
